### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by seogram** [passmarked/passmarked#39]
getting the following error when try to call api 

Error: Connection has been inactive (and missing pings from server) for more than 20 seconds

**Comment by Johanndutoit** [comment]
Looking at this as we speak, will revert in a few.

**Comment by Johanndutoit** [comment]
^ PR is in the queue, just waiting on testing to confirm all is well.

**Comment by Johanndutoit** [comment]
Live, feel free to re-open if this is a still an issue but think we got it
