### ISSUE TITLE
Handling error 

### ISSUE THREAD

**Issue by seogram** [passmarked/passmarked#43]
if the API doesn't work properly . it is not possible to fetch time out error . 

  passmarked.create({
    url:    targeturl,
      token : '........'
    }).on('done', function(result) {

codes inside done callback are executed even the API is not able to fetch data .

**Comment by skibz** [comment]
it appears as though you're not checking the error that's being emitted from the report `EventEmitter`.

try this:
```javascript
passmarked.create({
  url: targeturl,
  token : '........'
}).on('done', function(err, result) {
  if (err) {
    console.log('uh oh', err)
    return
  }
})
```

**Comment by seogram** [comment]
When I add err callback , then result becomes undefined .

**Comment by skibz** [comment]
it looks like there is a discrepancy between the code in the `samples` directory and the examples shown in the project readme.

in samples, the `done` event is shown to have an error parameter, but in source code i found a separate `error` event.

so with that in mind, can you try the following for me?
```javascript
passmarked.create({
  url: targeturl,
  token : '........'
}).on('error', function(err) {
  console.log('onerror', err)
}).start(function(err) {
  if (err) console.log('onstart error', err)
  else console.log('onstart')
})
```

**Comment by seogram** [comment]
the .on(error,...)   is not executed and the codes inside on('done') is being executed despite having error ;

     passmarked.create({
    url:    targeturl,
      token : '...'
  }).on('error',function(err){
    console.log(err);
  })
  .on('done', function(result) {

    result = result.toJSON();
    let issues = result.issues;        *****issues is undefined for some urls***** but error CB is not executed

  }).on('update', function(result) {

    console.log(result.countPendingTests() + '/' + result.countTests())
    }).start(function(err) {
    if (err) {
    res.json(err);
    }else 
     console.log('Report started')
    }

**Comment by Johanndutoit** [comment]
Howdy folks, ok so had a look at this. 

For a start, I think we'd need to make the docs a bit more clear on when these events are called. 

The `done` event will always be called even if we get a problem while trying to run it. The only difference would be that the result given back will have a result of `error`/`invalid`/`timeout` with the `getResult()` method.

For example:

```javascript
var passmarked = require('passmarked');
// create and run a report, waiting for it to finish
var report = passmarked.create({

  url:     '<url>',
  token:   '<token>'

});
report.on('error', function(err) {

  console.error(err)

});
report.on('done', function(result) {

  var code = result.getResult();

  if(code == 'success') {

    console.log('done with a score of ' + result.getScore())

  } else {

    console.log('failed with the result of: ' + code)

  }
  
  process.exit(0)

});
report.start(function(err) {});
```

Would produce: 

```failed with the result of: error```

for one of the listed urls in https://github.com/passmarked/passmarked/issues/42

**Comment by Johanndutoit** [comment]
So @seogram I think next steps there, does this makes sense to you and did I understand this?

I will do a quick commit that updates our samples to make a bit more sense as well as a few quick edits to our docs

**Comment by seogram** [comment]
Thanks , It is clear now .

**Comment by Johanndutoit** [comment]
^ sample updates are in

**Comment by Johanndutoit** [comment]
@seogram I'll throw the ball in your court now, let me know if it makes sense and is workable in your app now then I'll close :)

**Comment by seogram** [comment]
sure , test it in hour

**Comment by seogram** [comment]
This issue has been solved .
