### ISSUE TITLE
address submission to passmarked api

### ISSUE THREAD

**Issue by skibz** [passmarked/passmarked#8]
if an address is encountered that has not yet been analysed, no score is returned.
there _is_ a websocket interface to submit and wait for a score, however.

**Comment by Johanndutoit** [comment]
"there is a websocket interface to submit and wait for a score, however." this will probably be the main function of the CLI though. 

Use case here is for someone to be able to download and use as part of scripts. So the default is to run a report, very happy with current capacity and the credits going live this week somewhere. 

Auth is all token based, ping me when you need details. Docs are on the way too ;)

Few things we talked about:

-> Run one or multiple reports by just going to "passmarked io.co.za/about-us" 
-> filtering out error level, IE. I only want to see errors.
-> Spit out complete JSON for report when it's done
-> ignore certain rules, so a --ignore flag or something.

Then on the second use case it could be used to query with a subdomain for the average of the domain. 

Thoughts ?

**Comment by skibz** [comment]
@Johanndutoit https://github.com/passmarked/cli/issues/5#issuecomment-172994010

**Comment by skibz** [comment]
i'll get started on this tomorrow morning :relaxed:
